# Generated by Django 2.0.3 on 2019-04-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_itemfororder_cheeseextra'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderhistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('itemname', models.CharField(max_length=64)),
                ('price', models.CharField(max_length=64)),
            ],
        ),
    ]
